name: Testing workflow variables

on: 
  workflow_dispatch

env: 
  cloud: google-cloud

jobs:
  greeting_jobs:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps: 
      - name: "Its Friday"
        run: echo "$Greeting $First_Name is using $cloud!"
        env: 
          First_Name: Naman
